name: Wakapi Update Stats

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: xyvs/wakapi-readme-stats@v0.2
        with:
          WAKATIME_URL: ${{ secrets.WAKATIME_URL }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: False
          SHOW_PROJECTS: False
          SHOW_PROFILE_VIEWS: False
          SHOW_LINES_OF_CODE: True
          COMMIT_BY_ME: True
